services:
  postgres:
    image: postgres:16
    container_name: qpang-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userservice
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # 데이터 영구 보관용

  redis:
    image: redis:7-alpine
    container_name: qpang-redis
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin:2
    container_name: qpang-zipkin
    ports:
      - "9411:9411"
