spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qpang_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kakao:
  api:
    key: ${KAKAO_REST_API_KEY:your_actual_key_here}