spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hubs/**

        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

jwt:
  secret:
    key: ${JWT_SECRET_BASE64}
