spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**,/users/**

        # order-service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        # delivery
        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/deliveries/**

        # product-service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        # company-service
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/companies/**

        # hub-service
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/hubs/**,/api/hub-routes/**

        # delivery-manager
        - id: delivery-manager
          uri: lb://delivery-manager
          predicates:
            - Path=/api/delivery-managers/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**,/messages/**,/ai/**

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

jwt:
  secret:
    key: ZGVsaXZlcnktc2VjcmV0LWtleS1kZWxpdmVyeS1zZWNyZXQta2V5LWRlbGl2ZXJ5