spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=api/orders/**

server:
  port: 18080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/